# ~/.config/bashrc.d/20-password-store.sh

PASSWORD_STORE_DIR="$HOME/.password-store"
PASSWORD_STORE_GENERATED_LENGTH="24"
PASSWORD_STORE_ENABLE_EXTENSIONS="true"
PASSWORD_STORE_EXTENSIONS_DIR=".extensions"
PASSWORD_STORE_DIR="$HOME/.password-store"
PASSWORD_STORE_SIGNING_KEY="0xDDD127EAF8574CB4"
