#!/usr/bin/env sh

tmux_current_session () {
    if [ "$TMUX" ]; then
        tmux display-message -pF '#{client_session}'
    fi
}

tmux_current_session "$@"

#tmux list-sessions | awk -F: '/\(attached\)/ { print $1 }'
