#!/usr/bin/env sh
# alacritty -e zsh -c tmux_new_or_attach_session

SESSION=${1:-mytmux}

tmux_attach () {
    tmux attach -t $session
}

# abort if we're already inside a TMUX session
[ "$TMUX" == "" ] || exit 0

tmux_new_session () {
    # home
    tmux new-session -n "home" -s $session -c "$HOME" -d
    tmux send-keys -t $SESSION "clear && ls -lh" C-m
    tmux split-window -v -p 50 -t $session -c "$HOME"
    tmux send-keys -t $SESSION:1.2 "clear" C-m
    # work
    tmux new-window -n "work" -t $session -c "$HOME"
    tmux send-keys -t $SESSION:2 "clear" C-m
    tmux split-window -v -p 50 -t $session -c "$HOME"
    tmux send-keys -t $SESSION:2.2 "clear" C-m
    tmux select-window -t $SESSION:1:2
    tmux attach -t $SESSION
}

tmux has-session -t $SESSION && tmux_attach || tmux_new_session
