#! /bin/sh
#
# BSPWM - Binary space partitioning window manager


# -----------------------------------------------------------------------------
# Window Management
# -----------------------------------------------------------------------------

# See `man bspc` and `man bspwm`

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 2
bspc config window_gap 10
bspc config split ratio 0.5
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc config focus_by_distance true
bspc config history_aware_focus true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_action1 move # alt + left-click to move node
bspc config pointer_action2 resize_side # alt + right-click to resize node splits

# Assign apps to workspaces
bspc rule -a URxvt desktop='^1'
bspc rule -a Spacefm desktop='^2'
bspc rule -a Chromium-browser-chromium desktop='^3'
bspc rule -a Gimp desktop='^5'

# Floating apps
bspc rule -a NeovimGtk "state=floating"
bspc rule -a Lxtask "state=floating"
bspc rule -a Lxappearance state=floating

# Program-specific rules (use `xprop` to find each window's specifics)
# For special use cases, I apply "my_float_window" for programs that can
# accept a custom name/class. These two definitions apply a custom
# class and name respectively
bspc rule -a my_float_window:* state=floating
bspc rule -a *:my_float_window state=floating

# External window rules
bspc config external_rules_command "$(which external_rules)"


# -----------------------------------------------------------------------------
# Colors
# -----------------------------------------------------------------------------

bspc config normal_border_color "#312e30" # unfocused window
bspc config active_border_color "#b58d88" # focused window, unfocused monitor
bspc config focused_border_color "#6da280" # focused window, focused monitor
bspc config presel_feedback_color "#2a2829" # feedback for manual node split


# -----------------------------------------------------------------------------
# Autostart
# -----------------------------------------------------------------------------

# The hotkey daemon that handles all custom key bindings, including control of BSPWM
sxhkd &
# Launch custom lemonbar
pgrep -x avocado_panel && pkill -x avocado_panel
avocado_panel &
# Compton Compositor
compton -b &
# Wallpaper
random-wallpaper &

# Launch URxvt daemon to start any number of terminal windows from within a single process,
# which startup very fast and reduces memory usage. (Unix domain socket ${XDG_RUNTIME_DIR}/urxvtd)
urxvtd --quiet --opendisplay --fork &

# Launch Spacefm file-manager daemon
pgrep -x spacefm && pkill -x spacefm
spacefm --daemon-mode --no-desktop &

# Redshift
pgrep -x redshift && pkill -x redshift
redshift &

# Unclutter
pgrep -x unclutter && pkill -x unclutter
unclutter &

# vim:fenc=utf-8:ft=sh:
