#! /bin/sh

if ! bspc wm -g &>/dev/null; then
    exit 1
fi

sxhkd &
random-wallpaper.sh &
${XDG_CONFIG_HOME}/polybar/launch.sh &
${XDG_CONFIG_HOME}/compton/launch.sh &
${XDG_CONFIG_HOME}/spacefm/launch.sh &

urxvtd --quiet --opendisplay --fork &
redshift-gtk &
unclutter &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split ratio             0.5
bspc config focus_follows_pointer   true
bspc config ignore_ewmh_focus       true
bspc config focus_by_distance       true
bspc config history_aware_focus     true
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# assign to workspaces
bspc rule -a URxvt desktop='^1'
bspc rule -a Spacefm desktop='^2'
bspc rule -a Chromium-browser-chromium desktop='^3'
bspc rule -a Gimp desktop='^5' state=floating follow=on

# floating apps
bspc rule -a NeovimGtk "state=floating"
bspc rule -a Lxtask "state=floating"
bspc rule -a lxappearance state=floating
