default-remote: local
remotes:
  images:
    addr: https://images.linuxcontainers.org
    protocol: simplestreams
    public: true
  local:
    addr: unix://
    public: false
aliases:
  login: exec $ARGS@ -- sudo --user $@${USER:-root} --login
  ubuntu: exec @ARGS@ --user 1000 --group 1000 --env HOME=/home/ubuntu -- /bin/bash
    --login
